Command_List:
    - Command_defult: &base
        name: base
        type: read
        parser_style: get_result
        parser_offset: 0
        send_code: 0
        receive_code: 0
        receive_len: 0
        receive_delay: 100
        rts_control: off
        rts_delay: 0
        write_argv: 0
        verify: crc
        size: 0
    - Command1:
        <<: *base # 引用 base 锚点，实例化时会自动展开
        name: 耳机进产测
        type: write
        parser_style: results
        send_code: FE314000000100014F4E
        receive_code: FE134080
        receive_len: 0
    - Command2:
        <<: *base
        name: 耳机退产测
        type: read
        parser_style: results
        send_code: FE314000000100006E5E
        receive_code: FE134080
        receive_len: 0
    - Command3:
        <<: *base
        name: 耳机查询产测模式
        type: read
        parser_style: get_result
        send_code: FE314100000000CB3D
        receive_code: FE134080
        receive_len: 0
    - Command4:
        <<: *base
        name: 耳机进电量管控
        type: write
        parser_style: results
        send_code: FE318A00000400
        receive_code: FE134080
        receive_len: 0
        write_argv: power_control
    - Command5:
        <<: *base
        name: 耳机读电量管控
        type: read
        parser_style: get_result
        send_code: FE314100000000CB3D
        receive_code: FE134080
        receive_len: 0
    - Command6:
        <<: *base
        name: 耳机蓝牙地址
        type: read
        parser_style: get_mac
        send_code: FE315000000000C093
        receive_code: FE135080
        receive_len: 0
    - Command7:
        <<: *base
        name: 耳机软件版本
        type: read
        parser_style: get_string
        send_code: FE3144000000009C1E
        receive_code: FE134480
        receive_len: 0
    - Command8:
        <<: *base
        name: 耳机硬件版本
        type: read
        parser_style: get_string
        send_code: FE31900000000078A0
        receive_code: FE139080
        receive_len: 0
    - Command9:
        <<: *base
        name: 耳机NTC温度
        type: read
        parser_style: get_string
        send_code: FE31460000010001AEC3
        receive_code: FE134680
        receive_len: 0
    - Command10:
        <<: *base
        name: 耳机电量电压
        type: read
        parser_style: get_string
        send_code: FE3174000000007212
        receive_code: FE137480
        receive_len: 0
    - Command11:
        <<: *base
        name: 耳机软复位
        type: read
        parser_style: results
        send_code: FE318300000000F04A
        receive_code: FE138380
        receive_len: 0
    - Command12:
        <<: *base
        name: 耳机关机
        type: read
        parser_style: results
        send_code: FE317300000000A675
        receive_code: FE137380
        receive_len: 0
    - Command13:
        <<: *base
        name: 耳机电量校准
        type: read
        parser_style: results
        send_code: FE313700000000C8ED
        receive_code: FE133780
        receive_len: 0
    - Command14:
        <<: *base
        name: 设置左右耳标志
        type: write
        parser_style: results
        send_code: FE313900000100
        receive_code: FE133980
        receive_len: 0
        write_argv: LR_flag
    - Command15:
        <<: *base
        name: 查询左右耳标志
        type: read
        parser_style: get_result
        send_code: FE3138000000003188
        receive_code: FE133880
        receive_len: 0

MES_List:
        
        
    
Test_List:
    - Command1
    - Command6
    - Command14
    - Command13
    - Command15
    - Command7
    - Command8
    - Command9
    - Command10
    - Command12